Feature: A payment authorization request is made against the Worldpay payment gateway

  Notes: the encryptedData value in the follow scenario is representative of the below test card details:
  - card number: 444333322221111
  - cvc: 123
  - expiry month: 5
  - expiry year: 2025
  - card holder name: 3D - this value is going to always trigger a test 3DS response from the API

  Scenario: Payment authorization with 3DS reply
    When I authorize the following payment
      | merchantCode     | SESSIONECOM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | orderCode        | 42796904                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | description      | trigger-3ds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | currencyCode     | GBP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | value            | 15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | encryptedData    | eyJhbGciOiJSU0ExXzUiLCJlbmMiOiJBMjU2R0NNIiwia2lkIjoiMSIsImNvbS53b3JsZHBheS5hcGlWZXJzaW9uIjoiMS4wIiwiY29tLndvcmxkcGF5LmxpYlZlcnNpb24iOiIxLjAuMSIsImNvbS53b3JsZHBheS5jaGFubmVsIjoiamF2YXNjcmlwdCJ9.Nbq0kZHzaLA_39cBG0pDSvj7jJbiSd2t51ZWKnJjA2c_zcoW2Nz1iXXrRz-SfPCUN6trqPUpE14WJknk2X1SzBCWkXCjUQfGBrpSVMm1Av4p7ikAvGEorRw7EeYZ4kL_ruJ-pYahobDslaFzqTvSWW5q25lPN2zBC8Ix0OLOtAVQ1M_4CTPpqj-aMLc-Mc7GS-pnjBLBlC5rnD_SiHRztzX6A9EJDbqOVq7LVquAsMbY40o9q79ZqYxdBFnYJVZ-2SlpHeGztfKxGN2BtWtHvF85Y3wK3m3UJqUwBoXmErsLa5q1B9wW4OsZsMgG5gQ2HaDZrVzkS0d1fHYijhxdLA.4qCvdqC6DEBKjSmQ.2fqIhHSneFnALH7Hno_e3xIN8tb_XSIzyTpNl3Uu4m3thPdiUVpEkiBbOKmRy2MDODw5GsSZdf5gTjAgTFIlyTZ0DI79XnQ4clmxI4jQj0MMhSZmpVdsXNX7KIjkgVLkLXvWVUdJNw4tMg.GzWUz0CUZP9SwB0S_DxDEA |
      | address1         | 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | address2         | Braford Gardens                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | address3         | Shenley Brook End                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | postalCode       | MK137QJ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | city             | Milton Keynes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | state            | Buckingamshire                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | countryCode      | GB                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | shopperIPAddress | 123.123.123.123                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | sessionId        | 0215ui8ib1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | email            | lpanainte+test@inviqa.com                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | acceptHeader     | text/html                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | userAgentHeader  | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    Then I should receive a 3d secure response
    And the response should reference the "42796904" order code
    And the response should reference a valid "paRequest" value
    And the response should reference the following issuerURL: "https://secure-test.worldpay.com/jsp/test/shopper/ThreeDResponseSimulator.jsp?orderCode=42796904"

  Scenario: 3D Secure payment authorisation completion
    When the authorization for the following payment is completed
      | merhantCode  | SESSIONECOM                                                                                                                                                                                                                                                                                                                                                                                           |
      | orderCode    | 42796904                                                                                                                                                                                                                                                                                                                                                                                              |
      | paResponse   | +fklha9G0+ZL4+dl+dgKra3lyLqS0rKulK8bcdajK6lxWxdJ9SzajwF0hJEdFFB0oaxUhbEnrtCBH5ibD9/hU8NlkJqa+i7APX0n/joy1LCrKDeHeC02rsQfs2zVFVXZMqwYhzT5e4h2K3oDdMShJxdEwZG3U825xYH21fWtv2si+yhzj8E9bArMMyNOG0OMi4BM+d3iwEPOFmAHrcDjbcmFZt6a253MObIiAWZAy+/vEwDMpPx7Q9VxXZHOA/dyB9eL24Q75wG7jWBSSd4RGlo+iPLEQz8A6HHSTNq3GOFrvkngTryNgdwiy9HLB7b9TdxSgTCL3jTpzdlnhqaiVbI6l1fwIALOaWPfWCAfztKaZItYtvvsbljL8M09fTZe79g== |
      | merchantCode | SESSIONECOM                                                                                                                                                                                                                                                                                                                                                                                           |
      | sessionId    | 0215ui8ib1                                                                                                                                                                                                                                                                                                                                                                                            |
      | cookie       | cookie val                                                                                                                                                                                                                                                                                                                                                                                            |
    Then I should receive an authorised response
    And the response should be successful
    And the response should reference the "42796904" order code

  Scenario: Failed 3D Secure payment authorisation completion
    When the authorization for the following payment is completed
      | merhantCode  | SESSIONECOM      |
      | orderCode    | 42796904         |
      | paResponse   | trigger-an-error |
      | merchantCode | SESSIONECOM      |
      | sessionId    | 0215ui8ib1       |
      | cookie       | cookie val       |
    Then I should receive an authorised response
    And the response should not be successful
    And the response error message should be "An internal CSE service error has occurred."
    And the response error code should be "5"