Feature: A payment authorization request is made against the Worldpay payment gateway using Apple Pay

    Scenario: Generate Apple pay auth request xml
        When I generate apple pay xml with the following details
            | merchantCode  | REISSECOMGBP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
            | orderCode     | 77766633301                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | description   | This is a beautiful order                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
            | currencyCode  | GBP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | value         | 15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
            | encryptedData | eyJhbGciOiJSU0ExXzUiLCJlbmMiOiJBMjU2R0NNIiwia2lkIjoiMSIsImNvbS53b3JsZHBheS5hcGlWZXJzaW9uIjoiMS4wIiwiY29tLndvcmxkcGF5LmxpYlZlcnNpb24iOiIxLjAuMSIsImNvbS53b3JsZHBheS5jaGFubmVsIjoiamF2YXNjcmlwdCJ9.dRLdwIEaFobISQRn7Nw_CSuDPcdyD_ssic5NWP838bEnqqaiv1NROkM_hEzGssVXIS4384vtmgc7ZeScIaNAuckEGeA3L8Fr_ucpxCtS0w05VadzqzQLSX1SOFDRnWxjBKh2zX2JpPOPBjXZXpIwwTx4k3jxaxbqzjAzcz2IgpDvIVHJGJ45ziRD8H9LmjN_3sx-cFLEzDpsproz9VuioRtV2tFe0hWSxxA1dGOhS0renspASmmMWznfAv48tDMPkGDBQeCUkCFEdy5fyTP6vwo__eLWwDWThexPI750MH6yDAb6ZMlN_DcN-B3MDjYRNx9tuJK9uYZVOKx1HM8pvg.H5bv_exIuNXZcZ6c.Ly05HljJ_2d68dRATe2uKH6eN1qdE-AOWj0YRIMFsyCumH4QbVh4X_y0KGfcb9ORCLxEhCIF3Nfw5GZYW3FCecT24zpAljHfeVQjHmZxAcYB2BxuTfpkdCnGG4e6SD5Ohg60Gy-34P-fbcj4.tBCqnBmDyNeS8ZDxtYCGpQ |
            | email         | lpanainte+test@inviqa.com                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
        Then the generated XMl should match the following xml
"""
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paymentService PUBLIC "-//Worldpay//DTD Worldpay PaymentService v1//EN" "http://dtd.worldpay.com/paymentService_v1.dtd"><paymentService version="1.4" merchantCode="REISSECOMGBP">
 <submit>
  <order orderCode="77766633301">
   <description>This is a beautiful order</description>
   <amount currencyCode="GBP" exponent="2" value="15"/>
   <paymentDetails>
    <APPLEPAY-SSL>
     <header>
      <ephemeralPublicKey>dummy public key</ephemeralPublicKey>
      <publicKeyHash>dummy hash</publicKeyHash>
      <transactionId>123456</transactionId>
     </header>
     <signature>dummy signature</signature>
     <version>dummy version</version>
     <data>eyJhbGciOiJSU0ExXzUiLCJlbmMiOiJBMjU2R0NNIiwia2lkIjoiMSIsImNvbS53b3JsZHBheS5hcGlWZXJzaW9uIjoiMS4wIiwiY29tLndvcmxkcGF5LmxpYlZlcnNpb24iOiIxLjAuMSIsImNvbS53b3JsZHBheS5jaGFubmVsIjoiamF2YXNjcmlwdCJ9.dRLdwIEaFobISQRn7Nw_CSuDPcdyD_ssic5NWP838bEnqqaiv1NROkM_hEzGssVXIS4384vtmgc7ZeScIaNAuckEGeA3L8Fr_ucpxCtS0w05VadzqzQLSX1SOFDRnWxjBKh2zX2JpPOPBjXZXpIwwTx4k3jxaxbqzjAzcz2IgpDvIVHJGJ45ziRD8H9LmjN_3sx-cFLEzDpsproz9VuioRtV2tFe0hWSxxA1dGOhS0renspASmmMWznfAv48tDMPkGDBQeCUkCFEdy5fyTP6vwo__eLWwDWThexPI750MH6yDAb6ZMlN_DcN-B3MDjYRNx9tuJK9uYZVOKx1HM8pvg.H5bv_exIuNXZcZ6c.Ly05HljJ_2d68dRATe2uKH6eN1qdE-AOWj0YRIMFsyCumH4QbVh4X_y0KGfcb9ORCLxEhCIF3Nfw5GZYW3FCecT24zpAljHfeVQjHmZxAcYB2BxuTfpkdCnGG4e6SD5Ohg60Gy-34P-fbcj4.tBCqnBmDyNeS8ZDxtYCGpQ</data>
    </APPLEPAY-SSL>
   </paymentDetails>
   <shopper>
    <shopperEmailAddress>lpanainte+test@inviqa.com</shopperEmailAddress>
   </shopper>
  </order>
 </submit>
</paymentService>

"""

    Scenario: Successful payment authorization via Apple Pay
        When I authorize the following payment using Apple Pay
            | merchantCode       | SESSIONECOM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
            | orderCode          | 32796901                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
            | description        | This is a beautiful order                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
            | currencyCode       | GBP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
            | value              | 15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | encryptedData      | eyJhbGciOiJSU0ExXzUiLCJlbmMiOiJBMjU2R0NNIiwia2lkIjoiMSIsImNvbS53b3JsZHBheS5hcGlWZXJzaW9uIjoiMS4wIiwiY29tLndvcmxkcGF5LmxpYlZlcnNpb24iOiIxLjAuMSIsImNvbS53b3JsZHBheS5jaGFubmVsIjoiamF2YXNjcmlwdCJ9.dKfhn7pnZKfMA4Sy8ODL30o0IAsJgGkYqgaObvWpahlhW2owo-Y3xwyeXc82_kd4UJ-UN4VNxJPuENYCNEa0iq4WE_vSMiBV9d_vZK91e-lJvpHqtucc9HI0T7fh5t7-QU0qhkLj_06W57hE3-HkKhI8-ZfOLbxN0XsQk7ZFpCrK4MT-IPJTk4Twrk2b9eAbnRuTMT-mFNh8lFeZZLp42FaTuLuchPGh1SqE3ln_1oUQppnm8mYkKWNgZlY3pjFpmJFlyrhK-7y-OxVz_FtKpd79fyxtAY1nLB_WO_gmAwFVGOnKwvdsTk_FDVPZ8lRe3LRLJ7pc9gzmw8oyH1gSRQ.dTOinx-7v0pFKvhA.8ZLx2l-HUrG6rFKOqELSyCNXw69CAEvY2F1xRoSiKtiHrxvmdBs5Wz_VPwjnYEEyhf-1Brioyq6A9O0NZZgmAMwk7GBbSKmxzoszbZ-ItSRumG714iDuQ0mqAYPPkq3bxY4mNavPreBXp7eXNg.IVkvoJ3Z2iH-6XgUMDR2LQ |
            | email              | lpanainte+test@inviqa.com                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
            | signature          | dummy signature                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | applePayVersion    | dummy version                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | ephemeralPublicKey | dummy public key                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
            | publicKeyHash      | dummy hash                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | transactionId      | 123456                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
        Then I should receive an authorised response
        And the response should be successful
        And the response should reference the 32796901 order code
        And the response should reference a valid machine cookie

